apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: certificate-dev
  namespace: dev
spec:
  secretName: dev-ca-tls
  issuerRef:
    name: cluster-issuer-letsencrypt-http
    kind: ClusterIssuer
  commonName: dev.servicefoundry.ca
  dnsNames:
    - dev.servicefoundry.ca
