
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: staging-ingress-route
  namespace: staging
spec:
  entryPoints:
    - web
    - websecure

  routes:

    - match: Host(`staging.servicefoundry.ca`) && PathPrefix(`/`)
      kind: Rule
      services:
        - name: staging-web-service
          port: 80

  tls:
    secretName: "staging-ca-tls"