apiVersion: v1
kind: ConfigMap
metadata:
  name: index-html
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Development</title>
    </head>
    <body>
        <h1>Development Page</h1>
    </body>
    </html>